server:
  port: ${SERVER_PORT:8081}
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          introspection-uri: ${INTROSPECTION_URI}
logging:
  level:
    org:
      springframework:
        security:
          config:
            annotation:
              web:
                configurers:
                  oauth2:
                    server:
                      resource:
                        OAuth2ResourceServerConfigurer: ${LOG_LEVEL:DEBUG}
          oauth2:
            client:
              userinfo:
                DefaultOAuth2UserService: ${LOG_LEVEL:DEBUG}
        web:
          client:
            RestTemplate: ${LOG_LEVEL:DEBUG}